# Copyright 2020-present, Mayo Clinic Department of Neurology
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brainmaze-zmq"
description = "BrainMaze: Brain Electrophysiology, Behavior and Dynamics Analysis Toolbox - ZeroMQ communication modules"
readme = "README.rst"
requires-python = ">=3.9.0"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Filip Mivalt", email = "mivalt.filip@mayo.edu"}
]
classifiers = [
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
]
version = "0.0.1"
dependencies = [
    "pyzmq",
    "pythonping",
    "tornado>=6.5",
]

[project.urls]
Homepage = "https://github.com/bnelair/brainmaze-zmq"
Documentation = "https://bnelair.github.io/brainmaze-zmq"
Repository = "https://github.com/bnelair/brainmaze-zmq"
"Bug Tracker" = "https://github.com/bnelair/brainmaze-zmq/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "sphinx>=7.0",
    "sphinx_book_theme",
]

[tool.setuptools]
packages = ["brainmaze_zmq"]
